import path from 'node:path';
import fs from 'fs-extra';
import type {
  MigrationAdapter,
  MigrateOpts,
  GenerateOpts,
  PlanResult,
  RunContext,
} from '../types.js';
import { UNSUPPORTED, isUnsupported } from '../types.js';
import { packageManagerExec, runCommand } from '../runner.js';

/**
 * Prisma migrations adapter.
 *
 * Maps Pillar operations to `prisma` subcommands:
 *
 *   | Pillar op  | Prisma command                                   |
 *   |------------|--------------------------------------------------|
 *   | generate   | prisma migrate dev --name X --create-only        |
 *   | migrate    | prisma migrate dev --name X                      |
 *   | deploy     | prisma migrate deploy                            |
 *   | status     | prisma migrate status                            |
 *   | reset      | prisma migrate reset --skip-seed --force         |
 *   | rollback   | (unsupported — Prisma has no native rollback)    |
 *
 * SQL preview uses `prisma migrate diff --from-migrations → --to-schema`
 * which prints the SQL statements that would be generated by the next
 * `migrate dev`, without touching the DB or the migrations folder.
 */
export class PrismaAdapter implements MigrationAdapter {
  readonly orm = 'prisma' as const;
  readonly displayName = 'Prisma';

  planGenerate(opts: GenerateOpts, ctx: RunContext): PlanResult {
    if (!opts.name) {
      return UNSUPPORTED(
        'Prisma migrations require a name',
        'Pass --name <slug>, e.g. `pillar db generate --name add_user_role`',
      );
    }
    return toPlan(
      ctx,
      `prisma migrate dev --name ${opts.name} --create-only`,
      ['prisma', 'migrate', 'dev', '--name', opts.name, '--create-only'],
      { destructive: false, applies: false },
    );
  }

  planMigrate(opts: MigrateOpts, ctx: RunContext): PlanResult {
    if (!opts.name) {
      return UNSUPPORTED(
        'Prisma migrate dev requires a name',
        'Pass --name <slug>, e.g. `pillar db migrate --name add_user_role`',
      );
    }
    return toPlan(
      ctx,
      `prisma migrate dev --name ${opts.name}`,
      ['prisma', 'migrate', 'dev', '--name', opts.name],
      { destructive: true, applies: true },
    );
  }

  planDeploy(ctx: RunContext): PlanResult {
    return toPlan(
      ctx,
      'prisma migrate deploy',
      ['prisma', 'migrate', 'deploy'],
      { destructive: true, applies: true },
    );
  }

  planStatus(ctx: RunContext): PlanResult {
    return toPlan(
      ctx,
      'prisma migrate status',
      ['prisma', 'migrate', 'status'],
      { destructive: false, applies: false },
    );
  }

  planReset(ctx: RunContext): PlanResult {
    return toPlan(
      ctx,
      'prisma migrate reset --skip-seed --force',
      ['prisma', 'migrate', 'reset', '--skip-seed', '--force'],
      { destructive: true, applies: true },
    );
  }

  planRollback(_ctx: RunContext): PlanResult {
    return UNSUPPORTED(
      'Prisma does not support migration rollbacks natively',
      'Create a new migration that reverses the change, or use `pillar db reset` in development.',
    );
  }

  /**
   * Compute the SQL the next `migrate dev` would write, by diffing the
   * applied migrations against the current schema file.
   *
   * We require `--exit-code` off here because a zero exit means "no
   * diff" on `migrate diff` — we want the SQL text regardless, and
   * decide "no pending changes" from empty stdout.
   */
  async previewSql(_opts: MigrateOpts, ctx: RunContext): Promise<string | null> {
    const schemaPath = await findPrismaSchema(ctx.projectRoot);
    if (!schemaPath) return null;

    const plan = toPlan(
      ctx,
      'prisma migrate diff (preview)',
      [
        'prisma', 'migrate', 'diff',
        '--from-migrations', path.join(path.dirname(schemaPath), 'migrations'),
        '--to-schema-datamodel', schemaPath,
        '--script',
      ],
      { destructive: false, applies: false },
    );
    if (isUnsupported(plan)) return null;

    try {
      const result = await runCommand(plan, ctx, { stream: false, stdin: 'ignore' });
      const text = result.stdout.trim();
      return text.length === 0 ? null : text;
    } catch {
      // `migrate diff` fails on misconfigured DBs or missing shadow DB.
      // Preview is best-effort — don't block the command on preview failure.
      return null;
    }
  }
}

async function findPrismaSchema(projectRoot: string): Promise<string | null> {
  const candidates = [
    path.join(projectRoot, 'prisma', 'schema.prisma'),
    path.join(projectRoot, 'schema.prisma'),
  ];
  for (const c of candidates) {
    if (await fs.pathExists(c)) return c;
  }
  return null;
}

function toPlan(
  ctx: RunContext,
  label: string,
  argv: string[],
  flags: { destructive: boolean; applies: boolean },
): PlanResult {
  const [bin, ...rest] = argv;
  if (!bin) return UNSUPPORTED('internal: empty argv');
  const exec = packageManagerExec(ctx.packageManager, bin, rest);
  return {
    label: `${ctx.packageManager === 'npm' ? 'npx' : ctx.packageManager} ${label}`,
    argv: exec.argv,
    cwd: ctx.cwd ?? ctx.projectRoot,
    destructive: flags.destructive,
    applies: flags.applies,
  };
}
