import path from 'node:path';
import fs from 'fs-extra';
import type { PillarConfig } from '../config/index.js';
import { MapManager } from '../map/index.js';
import type { MapNode } from '../map/types.js';
import { toPascalCase, pluralizeResource, findInterfaceBlock } from '../../utils/naming.js';

interface OpenAPISpec {
  openapi: string;
  info: { title: string; version: string; description: string };
  servers: Array<{ url: string }>;
  paths: Record<string, Record<string, PathOperation>>;
  components: { schemas: Record<string, SchemaObject> };
}

interface PathOperation {
  summary: string;
  operationId: string;
  tags: string[];
  parameters?: ParameterObject[];
  requestBody?: RequestBodyObject;
  responses: Record<string, ResponseObject>;
}

interface ParameterObject {
  name: string;
  in: string;
  required: boolean;
  schema: { type: string };
}

interface RequestBodyObject {
  required: boolean;
  content: { 'application/json': { schema: { $ref: string } } };
}

interface ResponseObject {
  description: string;
  content?: { 'application/json': { schema: unknown } };
}

interface SchemaObject {
  type: string;
  properties: Record<string, { type: string; format?: string }>;
  required?: string[];
}

/**
 * Generate an OpenAPI spec from the project map and source files.
 * Scans route files and model/types files to build the spec.
 */
export async function generateOpenAPISpec(
  projectRoot: string,
  config: PillarConfig,
): Promise<OpenAPISpec> {
  const mapManager = new MapManager(projectRoot);
  const map = await mapManager.load();

  const spec: OpenAPISpec = {
    openapi: '3.0.3',
    info: {
      title: config.project.name,
      version: '0.1.0',
      description: `API documentation for ${config.project.name} — generated by Pillar`,
    },
    servers: [{ url: 'http://localhost:3000' }],
    paths: {},
    components: { schemas: {} },
  };

  if (!map) return spec;

  // Find all resources by scanning the map for route/controller files
  const resources = discoverResources(map.structure, config);

  for (const resource of resources) {
    const basePath = `/${pluralizeResource(resource.name)}`;
    const pascalName = toPascalCase(resource.name);
    const pluralPascal = toPascalCase(pluralizeResource(resource.name));
    const tag = pascalName;

    // Read the types/model file to extract fields
    const fields = await extractFieldsFromSource(projectRoot, resource.typesPath);

    // Build schema
    spec.components.schemas[pascalName] = {
      type: 'object',
      properties: {
        id: { type: 'string', format: 'uuid' },
        ...Object.fromEntries(fields.map((f) => [f.name, { type: mapToOpenAPIType(f.type) }])),
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      required: ['id', ...fields.filter((f) => !f.optional).map((f) => f.name)],
    };

    spec.components.schemas[`Create${pascalName}Input`] = {
      type: 'object',
      properties: Object.fromEntries(fields.map((f) => [f.name, { type: mapToOpenAPIType(f.type) }])),
      required: fields.filter((f) => !f.optional).map((f) => f.name),
    };

    // Update payload: all fields optional (PATCH-friendly).
    spec.components.schemas[`Update${pascalName}Input`] = {
      type: 'object',
      properties: Object.fromEntries(fields.map((f) => [f.name, { type: mapToOpenAPIType(f.type) }])),
    };

    // Build paths
    const pluralReadable = pluralizeResource(resource.name);
    spec.paths[basePath] = {
      get: {
        summary: `List all ${pluralReadable}`,
        operationId: `findAll${pluralPascal}`,
        tags: [tag],
        responses: {
          '200': {
            description: `List of ${pluralReadable}`,
            content: { 'application/json': { schema: { type: 'array', items: { $ref: `#/components/schemas/${pascalName}` } } } },
          },
        },
      },
      post: {
        summary: `Create a new ${resource.name}`,
        operationId: `create${pascalName}`,
        tags: [tag],
        requestBody: {
          required: true,
          content: { 'application/json': { schema: { $ref: `#/components/schemas/Create${pascalName}Input` } } },
        },
        responses: {
          '201': {
            description: `${pascalName} created`,
            content: { 'application/json': { schema: { $ref: `#/components/schemas/${pascalName}` } } },
          },
        },
      },
    };

    spec.paths[`${basePath}/{id}`] = {
      get: {
        summary: `Get a ${resource.name} by ID`,
        operationId: `findOne${pascalName}`,
        tags: [tag],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          '200': {
            description: `${pascalName} found`,
            content: { 'application/json': { schema: { $ref: `#/components/schemas/${pascalName}` } } },
          },
          '404': { description: 'Not found' },
        },
      },
      put: {
        summary: `Update a ${resource.name}`,
        operationId: `update${pascalName}`,
        tags: [tag],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        requestBody: {
          required: true,
          content: { 'application/json': { schema: { $ref: `#/components/schemas/Update${pascalName}Input` } } },
        },
        responses: {
          '200': {
            description: `${pascalName} updated`,
            content: { 'application/json': { schema: { $ref: `#/components/schemas/${pascalName}` } } },
          },
        },
      },
      delete: {
        summary: `Delete a ${resource.name}`,
        operationId: `remove${pascalName}`,
        tags: [tag],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          '204': { description: 'Deleted' },
        },
      },
    };
  }

  return spec;
}

interface ResourceInfo {
  name: string;
  typesPath: string;
  controllerPath: string;
}

function discoverResources(structure: Record<string, MapNode>, config: PillarConfig): ResourceInfo[] {
  const resources: ResourceInfo[] = [];
  const ext = config.project.language === 'typescript' ? 'ts' : 'js';

  function walk(nodes: Record<string, MapNode>, currentPath: string): void {
    for (const [name, node] of Object.entries(nodes)) {
      const fullPath = currentPath ? `${currentPath}/${name}` : name;

      // Detect resource by presence of controller file
      if (name.endsWith(`.controller.${ext}`)) {
        const resourceName = name.replace(`.controller.${ext}`, '');
        const dir = currentPath;
        resources.push({
          name: resourceName,
          typesPath: `${dir}/${resourceName}.types.${ext}`,
          controllerPath: fullPath,
        });
      }

      if (node.children) {
        walk(node.children, fullPath);
      }
    }
  }

  walk(structure, '');
  return resources;
}

interface FieldInfo {
  name: string;
  type: string;
  optional: boolean;
}

async function extractFieldsFromSource(projectRoot: string, typesRelPath: string): Promise<FieldInfo[]> {
  const fullPath = path.join(projectRoot, typesRelPath);
  if (!(await fs.pathExists(fullPath))) return [];

  const content = await fs.readFile(fullPath, 'utf-8');
  const fields: FieldInfo[] = [];

  const baseName = path.basename(typesRelPath).replace(/\.(types|model)\.\w+$/, '');
  const pascalName = toPascalCase(baseName);

  const block = findInterfaceBlock(content, pascalName);
  if (!block) return fields;

  // Strip nested object literals so their keys don't leak into the field list.
  const interfaceBody = stripNestedObjects(block.body);

  // Match interface fields within the main interface body only
  const fieldRegex = /^\s+(\w+)(\?)?\s*:\s*(\w+)/gm;
  let match: RegExpExecArray | null;
  while ((match = fieldRegex.exec(interfaceBody)) !== null) {
    const name = match[1]!;
    // Skip standard fields and relation arrays
    if (['id', 'createdAt', 'updatedAt'].includes(name)) continue;
    const type = match[3] ?? 'string';
    // Skip relation fields (types that start with uppercase are likely other models)
    if (/^[A-Z]/.test(type) && type !== 'Date' && type !== 'Record') continue;
    fields.push({
      name,
      type,
      optional: match[2] === '?',
    });
  }

  return fields;
}

function stripNestedObjects(body: string): string {
  let out = '';
  let depth = 0;
  for (const ch of body) {
    if (ch === '{') { depth++; continue; }
    if (ch === '}') { depth = Math.max(0, depth - 1); continue; }
    if (depth === 0) out += ch;
  }
  return out;
}

function mapToOpenAPIType(tsType: string): string {
  const map: Record<string, string> = {
    string: 'string',
    number: 'number',
    boolean: 'boolean',
    Date: 'string',
    int: 'integer',
    float: 'number',
  };
  return map[tsType] ?? 'string';
}
